apps/spiderman/urls.py
from django.urls import path, re_path
from .views import SpiderDataView, AddDataToMysql, SpiderDataListView, AnswerView

app_name = "spider"

urlpatterns = [
    path('spiderdata/', SpiderDataView.as_view(), name='spiderdata'),
    # path('add/', AddDataToMysql.as_view(), name='add'),
    path('spiderdata/data/', SpiderDataListView.as_view(), name='data'),
    path('answer', AnswerView.as_view(), name='answer'),
]

jiemi/urls.py
from django.urls import path, include
from django.conf.urls.static import settings, static

urlpatterns = [
    path('thecode/', include("thecode.urls")),
    path('veri/', include("verification.urls")),
    path('spider/', include("spiderman.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/spiderman/models.py
from django.db import models
from utils.validators import MediaUrlValidator

# Create your models here.


class SpiderData(models.Model):
    """
    爬虫数据表
    """
    false_data = models.CharField('扰乱数据', max_length=200)
    true_data = models.CharField('真实数据', max_length=50)
    data_index = models.CharField('数据索引', max_length=150)
    image_url = models.CharField("图片url", validators=[MediaUrlValidator], null=False, max_length=30)
    order = models.IntegerField("排序", default=0)

    class Meta:
        db_table = 'tb_data'                    # 指定迁移时的表名
        verbose_name = '爬虫数据表'
        verbose_name_plural = verbose_name


class SpiderEncrypt(models.Model):
    encrypt_data = models.CharField('加密数据', max_length=150)
    spider = models.ForeignKey(SpiderData, related_name='spider', on_delete=models.CASCADE)


class PassSave(models.Model):
    """
    牛逼的记录表 需要 userid作为外键， 一个初始化时间(后期不变化)
    """
    arrive_date = models.DateTimeField(auto_now_add=True)
    arrive_ip = models.CharField(max_length=20, null=True)

    user = models.ForeignKey('thecode.User', on_delete=models.CASCADE)

    class Meta:
        db_table = 'tb_won'
        verbose_name = '通关记录表'
        verbose_name_plural = verbose_name

apps/spiderman/views.py
import logging
import random
import time
from django.shortcuts import render
from django.views import View
from django.shortcuts import redirect
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django_redis import get_redis_connection
from django.db.models import F

from utils.genData import InsertData
from utils.genJsonResponse import json_response
from utils.getUserMeta import get_ip
from utils.spyfilter import ReqFilter
from utils.res_code import *
from .constants import *
from .models import SpiderData, PassSave, SpiderEncrypt
# Create your views here.

logger = logging.getLogger('thegame')
logger2 = logging.getLogger('django')


@method_decorator(login_required, name='get')
class SpiderDataView(View):
    """
    url: spider/spiderdata
    返回数据页
    """

    def get(self, request):
        req_filter = ReqFilter()
        if req_filter.combine_general(request):
            return HttpResponse(PIKAQIU+BLOG_URL, status=418)
        logger2.info('有人访问 {}'.format(get_ip(request)))
        return render(request, 'spiderman/spiderdata.html')


@method_decorator(login_required, name='get')
class SpiderDataListView(View):
    """
    url: spider/spiderdata/data
    每一个请求给出5页
    """
    def get(self, request):
        # 访问redis，查看是否存在，存在返回皮卡丘
        ip = get_ip(request)
        redis_conn = get_redis_connection(alias='request_interval')
        if redis_conn.get('req_flag_{}'.format(ip)):
            return HttpResponse(MIGUAN, status=418)
        # 对请求进行鉴别
        req_filter = ReqFilter()
        if req_filter.combine_api_filter(request):
            return HttpResponse(BLOG_URL+PIKAQIU+MIGUAN, status=418)
        try:
            page = int(request.GET.get('page') or 1)
        except ValueError:
            return HttpResponse(PIKAQIU, status=418)
        # 获取查询集
        spider_data = SpiderData.objects.values(
            'false_data',  'data_index', 'image_url', 'order',
        ).annotate(encrypt_data=F('spider__encrypt_data')).order_by('id')

        # 分页
        paginator = Paginator(spider_data, 5)
        # 当前页数据
        spider_info = paginator.get_page(page)

        # 送入redis
        req_flag_key = 'req_flag_{}'.format(ip)
        # 让管道通知redis
        pl = redis_conn.pipeline()

        try:
            # 设置生存时间与value
            pl.setex(req_flag_key, REQUEST_INTERVAL, 1)
            # 让管道通知 redis 执行
            pl.execute()
        except Exception as e:
            logger2.error('redis 执行异常{}'.format(e))
            return json_response(errno=Code.UNKOWNERR, errmsg=error_map[Code.UNKOWNERR])

        data = {
            'total_pages': paginator.num_pages,
            'spider': list(spider_info)
        }
        return json_response(data=data)


@method_decorator(login_required, name='post')
class AnswerView(View):
    """
    答案页面
    """
    def get(self, request):
        pass_user = PassSave.objects.order_by('arrive_date').all()
        return render(request, 'spiderman/code.html', context={
            'ps': pass_user
        })

    def post(self, request):
        answer = request.POST.get('answer')
        if answer == '一别三季庆国庆月又新年':
            # 记录日志
            ip = get_ip(request)
            logger.info("{}, {}完成了挑战".format(request.user.username, get_ip(request)))
            # 记录到通关表
            if not PassSave.objects.filter(user=request.user).exists():
                ps = PassSave(user=request.user, arrive_ip=ip)
                ps.save()
            else:
                return HttpResponse('{} {} 已完成通关，勿重复提交'.format(request.user.username, ip))
            return HttpResponse("{} 恭喜你，攻略完毕，已计入排行".format(time.strftime('%Y-%m-%d %H:%M:%S')))
        else:
            return HttpResponse('不正确')


class AddDataToMysql(View):
    """
    url : spider/add
    写入数据库 部署时取消
    """
    def get(self, request):
        import random
        temp_list = []
        yibie = '₸3Ⱳq国q月又新年'
        chengyu = '左顾右盼、东张西望、望眼bai欲穿、极目远望、' \
                  '望洋兴叹、刮目相看、另眼du相看、走马观花、zhi瞠目而视、' \
                  '高步阔视、虎视眈眈、目不斜视、目不忍视、察颜观色、冷眼旁观、' \
                  '束手旁观、坐井观天兴高采烈、喜出望外、喜形于色、喜上眉梢、喜不自胜、' \
                  '喜不自禁、喜眉笑眼、喜气洋洋、喜笑颜开、笑逐颜开、心旷神怡、心满意足、心情舒畅' \
                  '、心醉神迷、心花怒放、乐乐陶陶、其乐融融、乐以忘忧、乐不可支、欣喜若狂'

        for i in range(1, 11):
            temp_dict = {'data': list(yibie)[i - 1], 'td': True, 'index': str(i)}
            temp_list.append(temp_dict)

        for i in range(1000):
            temp_dict = {'data': random.choice(chengyu.split('、')), 'index': '假的'}
            temp_list.append(temp_dict)

        random.shuffle(temp_list)

        if not temp_list[5].get('td'):
            temp_list[5] = {'data': 'A', 'td': 'True', 'index': '0'}
        else:
            temp_list.append({'data': 'A', 'td': 'True', 'index': '0'})
        count = 0
        for item in temp_list:
            shit_data = InsertData.shit_data()
            spi = SpiderData.objects.create(
                false_data=shit_data, true_data=item['data'], data_index=item['index'], order=count,
                image_url='{}.jpg'.format(random.randint(7, 8))
            )
            spi.save()
            spi.spider.create(encrypt_data=self.hanshu(spi.true_data))
            count += 1
        return HttpResponse('添加完成')

    @staticmethod
    def hanshu(s: str):
        return ''.join([chr(i2) for i2 in [ord(i)+2 for i in s]])

templates/spiderman/code.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>没有标题</title>


    <link rel="stylesheet" href="{% static 'css/spiderman/inputt.css' %}">


</head>

<body>
{% if msg %}
    <script>alert({{ msg }})</script>
{% endif %}

<div class="container">
    <form action="{% url 'spider:answer' %}" method="post">
        {% csrf_token %}
        <div class="section">
            <div class="container-input">
                <input class="text-input" type="text" placeholder=" " name="answer">
                <div class="clip-outer clip">
                    <div class="fill1 fill"></div>
                </div>
                <div class="clip-inner1 clip-inner clip">
                    <div class="fill"></div>
                </div>
                <div class="clip-inner2 clip-inner clip">
                    <div class="fill"></div>
                </div>
                <div class="clip-inner3 clip-inner clip">
                    <div class="fill"></div>
                </div>
                <div class="clip-inner4 clip-inner clip">
                    <div class="fill"></div>
                </div>
                <div class="clip-inner5 clip-inner clip">
                    <div class="fill"></div>
                </div>
                <div class="clip-inner6 clip-inner clip">
                    <div class="fill"></div>
                </div>
                <div class="clip-inner7 clip-inner clip">
                    <div class="fill"></div>
                </div>
            </div>
        </div>
        <input type="submit" placeholder="点一下">

    </form>
<div class="pass-order">
    <ul>
        <li class="li-title">当前排行 / 通关时间</li>
        {% for item in ps %}
            <li>{{ item.user.username }} &emsp;&emsp;{{ item.arrive_date }}</li>
        {% endfor %}
    </ul>
</div>


</div>

</body>

</html>

templates/spiderman/codeme.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CodeMe 庸了个白</title>
</head>
<body>

</body>
</html>

templates/spiderman/spiderdata.html
{% load static %}
<!doctype html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/spiderman/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/spiderman/demo_styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/spiderman/demo2.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/spiderman/default.css' %}">
    <script src="{% static 'js/spiderman/vendor/modernizr-2.6.2.min.js' %}"></script>
    <!--[if IE]>
		<script src="http://libs.baidu.com/html5shiv/3.7/html5shiv.min.js"></script>
	<![endif]-->
    <link rel="stylesheet" href="{% static 'css/spiderman/zhuangbicard/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/spiderman/zhuangbicard/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/spiderman/zhuangbicard/slick-theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/spiderman/zhuangbicard/style.css' %}">
</head>

<style>
    @font-face {
        font-family: 'Arial g';
        src: url("{% static 'fonts/arial.ttf' %}");
    }
    .codeme-box{
    width: 297px;
    height: 333px;
    background: #ffffff;
    margin: auto;
}
.codeme-title{
    background: #fbf69a;
    height: 90px;
    box-shadow: 0 1px 3px black;
    display: flex;
    color: #000;
}
.codeme-title .codeme-img{
    text-align: right;
    height: 100%;
}
.codeme-title .codeme-img img{
    height: 100%;
}
.codeme-title .codeme-item{
    text-align: left;
    height: 30px;
}
.codeme-title .codeme-item img{
    position: relative;
    height: 100%;
    left: 5px;
}

.codeme-contain{
    height: 243px;
}

</style>
<body class="dm-demo2">
<div class="htmleaf-container">

    <nav class="nav clearfix">
        <button class="nav-el" id="el-topleft" data-id="ov-topleft"></button>
        <button class="nav-el" id="el-topright" data-id="ov-topright"></button>
        <button class="nav-el" id="el-btmleft" data-id="ov-btmleft"></button>
        <button class="nav-el" id="el-btmright" data-id="ov-btmright"></button>
    </nav>

    <section class="overlay" id="ov-topleft">
        <div class="wrap">
            <div class="slide-container">

            </div>
        </div>
                <button class="close"><span class="mfg-cancel"></span></button>

    </section>
    <section class="overlay" id="ov-topright">
        <div class="wrap">
            <code>
                这个是凑数的
            </code>
        </div>
        <button class="close"><span class="mfg-cancel"></span></button>
    </section>
    <section class="overlay" id="ov-btmleft">
        <div class="wrap">
            <div class="codeme-box">
                <div class="codeme-contain">

                </div>
                <div class="codeme-title">
                    <div class="codeme-item">
                        <img src="{% static 'imgs/csdn.png' %}" alt="">
                        <a href="https://blog.csdn.net/qq_39177678" style="color: #5731ff">庸了个白:</a>
                        <a href="https://blog.csdn.net/qq_39177678">
                            <label for="codeme-item" style="text-align: left;color: #676262;font-family: 'Arial g'">
                        一个在Python领域苟且偷生一年半的小白, 姑且成长成大白(●—●)了
                    </label>
                        </a>

                    </div>

                    <div class="codeme-img">
                        <img src="{% static 'imgs/ylgbt.jpg' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
        <button class="close"><span class="mfg-cancel"></span></button>
    </section>
    <section class="overlay" id="ov-btmright">
        <div class="wrap">
            <a href="{% url 'spider:answer' %}"> <button>点这里</button></a>
        </div>
        <button class="close"><span class="mfg-cancel"></span></button>
    </section>
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/spiderman/slick.min.js' %}"></script>
<script src="{% static 'js/spiderman/plugins.js' %}"></script>
<script src="{% static 'js/spiderman/demo.js' %}"></script>
<script src="{% static 'js/spiderman/spiderdata.js' %}"></script>


<script type="text/javascript">
    setInterval(function(){debugger}, 1000);
    (function (){
        console.log("也许你已经发现了，" +
            "当你加载完数据的时候将会跳回第5页，不要慌张，" +
            "设定就是这么干的，我并不建议手动完成爬虫的工作，" +
            "当然如果你有足够耐心，我也不介意");

        var slideContainer = $('.slide-container');

        slideContainer.slick({
        });

    })();

</script>


</body>
</html>