apps/thecode/urls.py
from django.urls import path, re_path
from .views import ThecodeView, CommentsView, GetURL, RegisterView

app_name = "thecode"

urlpatterns = [
    path("", ThecodeView.as_view(), name="thecode"),
    path("comments/", CommentsView.as_view(), name="comments"),
    re_path("url=(?P<tag>register)/", GetURL.as_view(), name="geturl"),
    path("098f6bcd4621d373cade4e832627b4f6/", RegisterView.as_view(), name="register"),
]

apps/verification/urls.py
from django.urls import path, re_path
from .views import image_code_view, CheckEmailView, SendMailView, check_nickname_view

app_name = "veri"

urlpatterns = [
    path("image_code/", image_code_view, name="image_code"),
    path("email/", CheckEmailView.as_view(), name="email"),
    path("sendmail/", SendMailView.as_view(), name="sendmail"),
    re_path("check=(?P<nickname>.{2,20})/", check_nickname_view, name="nickname"),
]

jiemi/urls.py
from django.urls import path, include
from django.conf.urls.static import settings, static

urlpatterns = [
    path('thecode/', include("thecode.urls")),
    path('veri/', include("verification.urls")),
    path('spider/', include("spiderman.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/thecode/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
# Create your models here.


class User(AbstractUser):
    """
    AbstractUser原本已包含提示: username, first_name, last_name, email, is_active
    """
    class Meta:
        db_table = 'tb_user'                    # 指定迁移时的表名
        verbose_name = '用户'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username, self.email

apps/thecode/forms.py
import re
from urllib.parse import quote
from django import forms
from django.http import HttpResponse
from django.contrib.auth import login
from django.core.validators import RegexValidator
from django_redis import get_redis_connection

from .models import User
from .constants import *
from verification.forms import email_validator


# 昵称限制 5~20个字母或数字
nickname_validators = RegexValidator('^\w{2,20}$', 1)


class RegisterForm(forms.Form):
    
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super(RegisterForm, self).__init__(*args, **kwargs)

    nickname = forms.CharField(label='昵称', max_length=MAX_USERNAME_LENGTH, min_length=MIN_USERNAME_LENGTH,
                               validators=[nickname_validators],
                               error_messages={
                                   'max_length': '昵称长度错误',
                                   'min_length': '昵称长度错误',
                                   'validators': '昵称格式为2~20任意字符',
                                   'required': '昵称不能为空',
                               })
    password = forms.CharField(label='密码', max_length=MAX_PASSWORD_LENGTH, min_length=MIN_PASSWORD_LENGTH,
                               error_messages={
                                   'max_length': '密码长度错误',
                                   'min_length': '密码长度错误',
                                   'required': '密码不能为空',
                               })
    password_repeat = forms.CharField(label='重复密码', max_length=MAX_PASSWORD_LENGTH, min_length=MIN_PASSWORD_LENGTH,
                                      error_messages={
                                          'max_length': '密码最大长度为{}'.format(MAX_PASSWORD_LENGTH),
                                          'min_length': '密码长度至少为{}'.format(MIN_PASSWORD_LENGTH),
                                          'required': '密码不能为空',
                                      })

    email = forms.CharField(label='邮箱',
                            max_length=30, validators=[email_validator, ],
                            error_messages={
                                 'max_length': '邮箱长度错误',
                                 'min_length': '邮箱长度错误',
                                 'required': '邮箱不能为空',
                             })
    mailcode = forms.CharField(label='邮箱验证码', error_messages={'required': '验证码不能为空'})

    def clean_nickname(self):
        nickname = self.cleaned_data.get('nickname')
        if User.objects.filter(username=nickname).exists():
            raise forms.ValidationError('昵称已存在')
        return nickname

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('邮箱已被注册')
        return email

    def clean(self):
        cleaned_data = super().clean()
        nickname = cleaned_data.get('nickname')
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')
        password_repeat = cleaned_data.get('password_repeat')
        mailcode = cleaned_data.get('mailcode')

        # 校验两次输入的密码是否一致
        if password != password_repeat:
            raise forms.ValidationError('两次输入的密码不一致')

        # 校验验证码是否正确
        # 连接redis
        redis_conn = get_redis_connection(alias='mailcode')
        real_em_code = redis_conn.get('em_text_{}'.format(email))
        if not real_em_code and mailcode != real_em_code:
            raise forms.ValidationError('邮箱验证码错误')

        return cleaned_data


class LoginForm(forms.Form):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super(LoginForm, self).__init__(*args, **kwargs)

    nickname = forms.CharField(error_messages={'required': '请输入正确的昵称或密码'})

    password = forms.CharField(label='密码', max_length=MAX_PASSWORD_LENGTH, min_length=MIN_PASSWORD_LENGTH,
                               error_messages={
                                   'max_length': '密码长度错误',
                                   'min_length': '密码长度错误',
                                   'required': '密码不能为空',
                               })
    rand = forms.CharField(label="随机")

    def clean_account(self):
        nickname = self.cleaned_data.get('nickname')
        if not re.match('^\w{2,20}$', nickname):
            raise forms.ValidationError('昵称或密码输入错误')
        return nickname

    def clean(self):
        cleaned_data = super().clean()
        rand = cleaned_data.get('rand')
        if not rand:
            raise forms.ValidationError("爬虫警告")
        nickname = cleaned_data.get('nickname')
        password = cleaned_data.get('password')

        # 找到用户，校验密码
        user_querySet = User.objects.filter(username=nickname)
        if user_querySet:
            user = user_querySet.first()
            if user.check_password(password):
                # 免登陆
                # self.request.session.set_expiry(REMENBER_LOGIN_TIME * 24 * 60 * 60)
                self.request.session.set_expiry(DEFAULT_LOGIN_TIME * 60)
                print(dir(self.request))
                print(self.request.COOKIES)
                login(self.request, user)
            else:
                raise forms.ValidationError('昵称或密码输入错误')
        else:
            raise forms.ValidationError('昵称或密码输入错误')

        return cleaned_data

apps/thecode/views.py
import logging
from django.shortcuts import render
from django.views import View

from .forms import RegisterForm, LoginForm
from .models import User

from utils.genJsonResponse import json_response
from utils.res_code import *
from utils.getUserMeta import get_ip

# Create your views here.

logger = logging.getLogger('thegame')
logger2 = logging.getLogger('django')


class ThecodeView(View):
    """
    入口页视图
    url:thecode/
    """
    def get(self, request):
        logger2.info('有人访问 {}'.format(get_ip(request)))
        return render(self.request, "thecode/thecode.html")

    def post(self, request):
        # 校验数据
        form = LoginForm(request.POST, request=request)
        if form.is_valid():
            return json_response(errno=Code.OK, errmsg='登录成功')
        else:
            # 将表单错误信息进行拼接
            err_msg_str = '/'.join([item[0] for item in form.errors.values()])
            return json_response(errno=Code.PARAMERR, errmsg=err_msg_str)


class CommentsView(View):
    """
    活动解释页
    url:thecode/comments
    """
    def get(self, request):
        return render(self.request, "thecode/comments.html")


class GetURL(View):
    """
    返回url
    url:thecode/url=register
    """
    def get(self, request, tag):
        if tag == "register":
            data = {
                "url": "/thecode/098f6bcd4621d373cade4e832627b4f6"
            }
            return json_response(data=data)
        return json_response(errno=Code.PARAMERR, errmsg=error_map[Code.PARAMERR])


class RegisterView(View):
    """
    注册视图
    url: thecode/098f6bcd4621d373cade4e832627b4f6
    """
    def get(self, request):
        return render(request, "thecode/register.html")

    def post(self, request):
        # 1.校验数据
        form = RegisterForm(request.POST, request=request)
        if form.is_valid():
            # 新建数据
            nickname = form.cleaned_data.get('nickname')
            password = form.cleaned_data.get('password')
            email = form.cleaned_data.get('email')
            # 新建用户
            User.objects.create_user(username=nickname, password=password, email=email)
            # 注册成功记录 IP name 邮箱
            # logger.info('{} {} {}'.format())
            return json_response(errmsg='注册成功')
        else:
            # 将表单错误信息进行拼接
            err_msg_str = '/'.join([item[0] for item in form.errors.values()])

            return json_response(errno=Code.PARAMERR, errmsg=err_msg_str)

templates/thecode/register.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
希望你不要后悔自己的决定
{% endblock %}

{% block links %}
    <link rel="stylesheet" href="{% static 'css/thecode/thecode.css' %}">
{% endblock %}

{% block container %}
    <form action="#" method="post">
    {% csrf_token %}
            <div>
            <h3>希望你不要后悔自己的决定</h3>
            <ul>
                <li>
                    <span><input type="text" name="nickname" placeholder="昵称" id="nickname"></span>
                <li>
                    <span><input type="password" name="password" placeholder="密码" id="pwd"></span>
                </li>
                <li>
                    <span><input type="password" name="password_repeat" placeholder="重复" id="pwd-repeat"></span>
                </li>
                <li>
                    <span><input type="text" name="email" placeholder="邮箱" id="email"></span>
                </li>
                <li>
                    <span><input type="text" name="image_code" placeholder="图形验证码" id="image_code"></span>
                    <span><img src="{% url 'veri:image_code' %}" alt="应该卡了" id="piccode"></span>
                </li>
                <li>
                    <span><input type="text" name="mailcode" placeholder="邮箱验证码"></span>
                    <span><button class="getmailcode">获取邮箱验证码</button></span>
                </li>

                <li>
                    <span><input type="submit" value="yepgo"></span>
                </li>
            </ul>
        </div>
    </form>

{% endblock %}

{% block script %}
    <script src="{% static 'js/thecode/register.js' %}"></script>
{% endblock %}

templates/thecode/thecode.html
{% extends "base.html" %}
{% load static %}

{% block links %}
    <link rel="stylesheet" href="{% static 'css/thecode/thecode.css' %}">
    <link rel="stylesheet" href="{% static 'css/thecode/extra.css' %}">
{% endblock %}

{% block title %}
    爬虫，你来了吗
{% endblock %}

{% block container %}

    <div class="container">
        <form action="#" method="post">
            {% csrf_token %}
            <div class="menu">
            <h3>那么，在哪注册呢</h3>
            <ul>
                <li>
                    <span><input type="text" name="nickname"></span>
                <li>
                    <span><input type="password" name="password"></span>
                </li>
                <li>
                    <span><input type="submit" value="yepgo"></span>
                </li>
            </ul>
        </div>
        </form>

        <div class="menu-btn-container">
            <button aria-pressed="false" aria-label="Open Menu" class="menu-btn"></button>
            <span class="menu-btn-pulse"></span>
            <span class="menu-btn-pulse"></span>
        </div>
        <svg>
            <symbol id="cog" viewBox="0 0 1024 1024">
                <path d="M390.71 1008.755c-2.109 0-4.248-0.262-6.378-0.81-45.976-11.803-90.149-30.042-131.291-54.21-11.923-7.003-16.13-22.21-9.501-34.344
                8.15-14.925 12.459-31.866 12.459-48.992 0-56.464-45.936-102.4-102.4-102.4-17.125 0-34.066 4.309-48.992 12.459-12.133 6.627-27.339
                2.421-34.342-9.501-24.17-41.142-42.408-85.315-54.211-131.293-3.333-12.989 3.92-26.349 16.629-30.629 41.699-14.037 69.717-53.034
                69.717-97.037s-28.018-83-69.718-97.040c-12.707-4.278-19.962-17.638-16.627-30.627 11.803-45.976 30.042-90.149 54.211-131.291 7.003-11.923 22.21-16.13
                34.344-9.501 14.923 8.15 31.864 12.459 48.99 12.459 56.464 0 102.4-45.936 102.4-102.4 0-17.126-4.309-34.067-12.459-48.99-6.629-12.134-2.422-27.341
                9.501-34.344 41.141-24.168 85.314-42.408 131.291-54.211 12.994-3.334 26.349 3.92 30.627 16.627 14.040 41.701 53.037 69.718 97.040 69.718s83-28.018
                97.038-69.717c4.28-12.71 17.645-19.965 30.629-16.629 45.976 11.802 90.15 30.042 131.293 54.211 11.922 7.003 16.128 22.208 9.501 34.342-8.152
                14.926-12.461 31.867-12.461 48.992 0 56.464 45.936 102.4 102.4 102.4 17.126 0 34.067-4.309 48.992-12.459 12.138-6.629 27.341-2.421 34.344 9.501
                24.166 41.141 42.406 85.314 54.21 131.291 3.334 12.989-3.918 26.349-16.627 30.627-41.701 14.040-69.718 53.037-69.718 97.040s28.018
                83 69.718 97.038c12.707 4.28 19.962 17.638 16.627 30.629-11.803 45.976-30.042 90.15-54.21 131.291-7.005 11.925-22.208 16.128-34.344
                9.502-14.926-8.152-31.867-12.461-48.992-12.461-56.464 0-102.4 45.936-102.4 102.4 0 17.125 4.309 34.066 12.461 48.992 6.627 12.136 2.421
                27.341-9.502 34.344-41.141 24.166-85.314 42.406-131.291 54.21-12.992 3.336-26.349-3.918-30.629-16.627-14.038-41.701-53.035-69.718-97.038-69.718s-83
                28.018-97.040 69.718c-3.578 10.624-13.502 17.437-24.25 17.437zM512 870.4c57.715 0 109.693 32.138 135.917 82.029 26.637-8.218 52.507-18.875
                77.299-31.846-5.541-16.077-8.416-33.075-8.416-50.182 0-84.696 68.904-153.6 153.6-153.6 17.107 0 34.106 2.875 50.181 8.418 12.971-24.792 23.63-50.662
                31.846-77.299-49.89-26.226-82.027-78.203-82.027-135.918s32.138-109.691 82.029-135.918c-8.218-26.637-18.875-52.506-31.846-77.299-16.077 5.542-33.074
                8.418-50.182 8.418-84.696 0-153.6-68.904-153.6-153.6 0-17.107 2.875-34.106 8.418-50.181-24.792-12.971-50.662-23.63-77.299-31.846-26.226 49.89-78.203
                82.027-135.918 82.027s-109.691-32.138-135.917-82.027c-26.637 8.216-52.507 18.874-77.299 31.846 5.542 16.075 8.416 33.072 8.416 50.181 0 84.696-68.904
                153.6-153.6 153.6-17.109 0-34.106-2.874-50.181-8.418-12.973 24.794-23.63 50.662-31.846 77.299 49.89 26.227 82.027 78.203 82.027 135.918s-32.138
                109.693-82.027 135.917c8.216 26.637 18.875 52.507 31.846 77.299 16.075-5.541 33.074-8.416 50.181-8.416 84.696 0 153.6 68.904 153.6 153.6 0 17.109-2.875
                34.106-8.418 50.181 24.794 12.971 50.662 23.63 77.299 31.846 26.227-49.89 78.203-82.027 135.918-82.027z"></path>
                <path d="M512 665.6c-84.696 0-153.6-68.904-153.6-153.6s68.904-153.6 153.6-153.6 153.6 68.904 153.6 153.6-68.904 153.6-153.6 153.6zM512 409.6c-56.464 0-102.4
                 45.936-102.4 102.4s45.936 102.4 102.4 102.4c56.464 0 102.4-45.936 102.4-102.4s-45.936-102.4-102.4-102.4z"></path>
            </symbol>
            <symbol id="picture" viewBox="0 0 1024 1024">
                <path d="M947.2 1024h-870.4c-42.347 0-76.8-34.451-76.8-76.8v-870.4c0-42.347 34.453-76.8 76.8-76.8h870.4c42.349 0 76.8 34.453 76.8 76.8v870.4c0 42.349-34.451
            76.8-76.8 76.8zM76.8 51.2c-14.115 0-25.6 11.485-25.6 25.6v870.4c0 14.115 11.485 25.6 25.6 25.6h870.4c14.115 0 25.6-11.485 25.6-25.6v-870.4c0-14.115-11.485-25.6-25.6-25.6h-870.4z"></path>
                <path d="M665.6 460.8c-56.464 0-102.4-45.936-102.4-102.4s45.936-102.4 102.4-102.4 102.4 45.936 102.4 102.4-45.936 102.4-102.4 102.4zM665.6 307.2c-28.232 0-51.2
            22.968-51.2 51.2s22.968 51.2 51.2 51.2 51.2-22.968 51.2-51.2-22.968-51.2-51.2-51.2z"></path>
                <path d="M896 102.4h-768c-14.138 0-25.6 11.462-25.6 25.6v614.4c0 14.139 11.462 25.6 25.6 25.6h768c14.139 0 25.6-11.461 25.6-25.6v-614.4c0-14.138-11.461-25.6-25.6-25.6zM153.6
            598.533l164.318-184.858c4.203-4.728 9.694-7.371 15.462-7.44 5.725-0.090 11.322 2.438 15.638 7.062l283.27 303.502h-478.69v-118.267zM870.4
            716.8h-168.075l-315.875-338.437c-14.269-15.288-33.312-23.605-53.691-23.325-20.354 0.246-39.214 8.992-53.107 24.621l-126.051 141.808v-367.867h716.8v563.2z"></path>
            </symbol>
            <symbol id="lock" viewBox="0 0 1024 1024">
                <path d="M813.412,360.894h-30.141v-90.424C783.271,120.891,661.579-0.8,512-0.8S240.729,120.891,240.729,270.471v90.423h-30.141
            c-49.859,0-90.424,40.565-90.424,90.424v482.259c0,49.859,40.565,90.424,90.424,90.424h602.823
            c49.859,0,90.424-40.565,90.424-90.424V451.318C903.835,401.459,863.271,360.894,813.412,360.894L813.412,360.894z M301.012,270.471
            c0-116.339,94.649-210.988,210.988-210.988s210.988,94.649,210.988,210.988v90.423H301.012L301.012,270.471L301.012,270.471z
                M843.553,933.576c0,16.619-13.522,30.141-30.141,30.141H210.588c-16.619,0-30.141-13.522-30.141-30.141V451.318
            c0-16.619,13.522-30.141,30.141-30.141h602.823c16.619,0,30.141,13.522,30.141,30.141V933.576z"/>
            </symbol>
        </svg>

    </div>
        <div class="siqi">
            <img src="{% static 'imgs/zlqtqbdmrhsnrqzdhlsc.png' %}" alt="">
        </div>

{% endblock %}

{% block script %}
    <script src="{% static 'js/thecode/TweenMax.min.js' %}"></script>
    <script src="{% static 'js/thecode/thecode.js' %}"></script>
    <script src="{% static 'js/thecode/extra.js' %}"></script>
{% endblock %}